FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt python-dotenv

# Use ARG for build-time variables
ARG STREAMLIT_DOMAIN
ARG STREAMLIT_PORT=5001

# Set environment variables
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
ENV STREAMLIT_SERVER_PORT=${STREAMLIT_PORT}
ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_SERVER_ENABLE_CORS=true
ENV STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
ENV STREAMLIT_BROWSER_SERVER_ADDRESS=${STREAMLIT_DOMAIN}

CMD ["streamlit", "run", "app.py"]