[project]
name = "repl-nix-multimodaldesignstudio"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.3",
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "openai>=1.59.3",
    "streamlit>=1.41.1",
]
