[server]
headless = true
address = "0.0.0.0"
port = 5001
enableWebsocketCompression = true
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 5

[browser]
serverAddress = "0.0.0.0"
serverPort = 5001
gatherUsageStats = false

[theme]
primaryColor = "#00f2ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1c24"
textColor = "#ffffff"
