[server]
headless = true
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00f2ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1c24"
textColor = "#ffffff"
